// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Assignment = 3,
  Name = 4,
  Number = 6,
  String = 7,
  Boolean = 8,
  Function_Call = 10,
  Term_Operator = 13,
  Expression_Operator = 14,
  If_Statement = 15,
  Conditional = 16,
  Logical_Operator = 17,
  Else_Statement = 20,
  While_statement = 21,
  For_Statement = 22,
  Initialization = 23
