// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Assignment = 2,
  Name = 3,
  Number = 4,
  String = 5,
  Boolean = 6,
  Function_Call = 8,
  If_Statement = 14,
  Conditional = 15,
  While_statement = 24,
  For_Statement = 25,
  Initialization = 26
